'use strict';

import {Deletable, Saveable} from "./commons";
import {DoctorMinimalView, IDoctor} from "./doctors";

export interface IdentifiableUser {
    username: string;
}
export interface UserBasicProps {
    name: string;
    doctor?: IDoctor;
    access?: Permit[];
}
export interface UserFinalDoctorProp {
    doctor: IDoctor | null;
}
export interface IUser extends IdentifiableUser, UserBasicProps, Deletable, Saveable {}
export interface IUserMinimalView extends IUser {
    doctor?: DoctorMinimalView;
}
export type User = IUser & UserFinalDoctorProp;
export type SignUpRequest = {
    username: string;
    name: string;
    password: string;
}
export interface UserPermit {
    action: Permit;
    user?: IdentifiableUser;
    allowed: boolean;
}
export type Permit = "CREATE_SPECIALTY" | "UPDATE_SPECIALTY" | "READ_DISABLED_SPECIALTY_RECORDS" | "DISABLE_SPECIALTY" | "ENABLE_SPECIALTY" | "CREATE_PATIENT" | "READ_PATIENT_PERSONAL_DATA" | "READ_PATIENT_APPOINTMENTS" | "UPDATE_PATIENT" | "DISABLE_PATIENT" | "ENABLE_PATIENT" | "CREATE_DOCTOR" | "READ_DOCTOR" | "READ_DOCTOR_APPOINTMENTS" | "UPDATE_DOCTOR_PERSONAL_DATA" | "UPDATE_DOCTOR_SCHEDULES" | "DISABLE_DOCTOR" | "ENABLE_DOCTOR" | "CREATE_APPOINTMENT" | "READ_APPOINTMENT" | "UPDATE_APPOINTMENT" | "DISABLE_APPOINTMENT" | "ENABLE_APPOINTMENT" | "GRANT_PERMISSIONS" | "ASSIGN_DOCTOR" | "RESET_PASSWORD" | "UPDATE_USER_DATA" | "DELETE_OR_ENABLE_USER" | "READ_USER_DATA" | "READ_USER_SESSIONS" | "CLOSE_USER_SESSIONS" | "UPDATE_TICKET" | "CREATE_TICKET" | "ENABLE_TICKET";
export const Permits = {
    CREATE_SPECIALTY: "CREATE_SPECIALTY",
    UPDATE_SPECIALTY: "UPDATE_SPECIALTY",
    READ_DISABLED_SPECIALTY_RECORDS: "READ_DISABLED_SPECIALTY_RECORDS",
    DISABLE_SPECIALTY: "DISABLE_SPECIALTY",
    ENABLE_SPECIALTY: "ENABLE_SPECIALTY",
    CREATE_PATIENT: "CREATE_PATIENT",
    READ_PATIENT_PERSONAL_DATA: "READ_PATIENT_PERSONAL_DATA",
    READ_PATIENT_APPOINTMENTS: "READ_PATIENT_APPOINTMENTS",
    UPDATE_PATIENT: "UPDATE_PATIENT",
    DISABLE_PATIENT: "DISABLE_PATIENT",
    ENABLE_PATIENT: "ENABLE_PATIENT",
    CREATE_DOCTOR: "CREATE_DOCTOR",
    READ_DOCTOR: "READ_DOCTOR",
    READ_DOCTOR_APPOINTMENTS: "READ_DOCTOR_APPOINTMENTS",
    UPDATE_DOCTOR_PERSONAL_DATA: "UPDATE_DOCTOR_PERSONAL_DATA",
    UPDATE_DOCTOR_SCHEDULES: "UPDATE_DOCTOR_SCHEDULES",
    DISABLE_DOCTOR: "DISABLE_DOCTOR",
    ENABLE_DOCTOR: "ENABLE_DOCTOR",
    CREATE_APPOINTMENT: "CREATE_APPOINTMENT",
    READ_APPOINTMENT: "READ_APPOINTMENT",
    UPDATE_APPOINTMENT: "UPDATE_APPOINTMENT",
    DISABLE_APPOINTMENT: "DISABLE_APPOINTMENT",
    ENABLE_APPOINTMENT: "ENABLE_APPOINTMENT",
    GRANT_PERMISSIONS: "GRANT_PERMISSIONS",
    ASSIGN_DOCTOR: "ASSIGN_DOCTOR",
    RESET_PASSWORD: "RESET_PASSWORD",
    UPDATE_USER_DATA: "UPDATE_USER_DATA",
    DELETE_OR_ENABLE_USER: "DELETE_OR_ENABLE_USER",
    READ_USER_DATA: "READ_USER_DATA",
    READ_USER_SESSIONS: "READ_USER_SESSIONS",
    CLOSE_USER_SESSIONS: "CLOSE_USER_SESSIONS",
    UPDATE_TICKET: "UPDATE_TICKET",
    CREATE_TICKET: "CREATE_TICKET",
    ENABLE_TICKET: "ENABLE_TICKET"
};
